### ISSUE TITLE
Drip stones turned into unknown nodes.

### ISSUE THREAD

**Issue by ghost** [FaceDeer/subterrane#7]
For some reason drip stones in my caves have turned into unknown nodes.
There are columns of "unknown nodes" where stalactites and stalagmites used to be.
Is it related to the latest update? If so perhaps it can be fixed with minetest.register_alias?

**Comment by FaceDeer** [comment]
I timed things poorly, sorry. :) I moved the explicit stalactite and stalagmite node definitions out of subterrane and into the dfcaverns mod, since subterrane is intended as a "library" mod that other mods make use of.  But I only put it into the sunless_sea branch of dfcaverns, which hasn't been merged back into the master branch yet. There are aliases defined in the sunless_sea branch of dfcaverns so the stalactites should come back if you use that, but in the meantime you might want to roll back subterrane - the only other modifications I made was adding features that only the sunless_sea branch of dfcaverns uses yet.

The sunless_sea branch is feeling almost ready to merge into dfcaverns master, I'll try to clean this up quickly.

**Comment by FaceDeer** [comment]
I've just put an option into subterrane to re-enable the old node definitions. ~~It's off by default, though, so you'll need to set the option "subterrane_enable_legacy_dripstone" to true to get them back.~~ Actually, I'll enable it by default for now. Fewer unexpected surprises that way, just in case.

In a couple of days I'll be merging sunless_sea into dfcaverns, and I don't think anything else will be using them after that.

**Comment by ghost** [comment]
That worked perfectly, no more unknown nodes.
Thanks for the quick fix!
